/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 3078be7c17f0271f322c318e73f5137ad4a3115e */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_gcurl_version, 0, 0, MAY_BE_ARRAY|MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, age, IS_LONG, 1, "null")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_TYPE_MASK_EX(arginfo_gcurl_init, 0, 0, GCurlHandle, MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, url, IS_STRING, 1, "null")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_impersonate, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, default_headers, _IS_BOOL, 0, "true")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_setopt, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
	ZEND_ARG_TYPE_INFO(0, option, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_MIXED, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_setopt_array, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_gcurl_exec, 0, 1, MAY_BE_STRING|MAY_BE_BOOL)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_getinfo, 0, 1, IS_MIXED, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, option, IS_LONG, 1, "null")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_errno, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_error, 0, 1, IS_STRING, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_strerror, 0, 1, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, error_code, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_reset, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

#define arginfo_gcurl_close arginfo_gcurl_reset

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_TYPE_MASK_EX(arginfo_gcurl_copy_handle, 0, 1, GCurlHandle, MAY_BE_FALSE)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_gcurl_multi_init, 0, 0, GCurlMultiHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_add_handle, 0, 2, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

#define arginfo_gcurl_multi_remove_handle arginfo_gcurl_multi_add_handle

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_exec, 0, 2, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
	ZEND_ARG_TYPE_INFO(1, still_running, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_select, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, timeout, IS_DOUBLE, 0, "1.0")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_gcurl_multi_info_read, 0, 1, MAY_BE_ARRAY|MAY_BE_FALSE)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(1, queued_messages, IS_LONG, 1, "null")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_getcontent, 0, 1, IS_STRING, 1)
	ZEND_ARG_OBJ_INFO(0, handle, GCurlHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_errno, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
ZEND_END_ARG_INFO()

#define arginfo_gcurl_multi_strerror arginfo_gcurl_strerror

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_close, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_multi_setopt, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, multi_handle, GCurlMultiHandle, 0)
	ZEND_ARG_TYPE_INFO(0, option, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_MIXED, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_gcurl_share_init, 0, 0, GCurlShareHandle, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_share_setopt, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, share_handle, GCurlShareHandle, 0)
	ZEND_ARG_TYPE_INFO(0, option, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_MIXED, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_gcurl_share_close, 0, 1, IS_VOID, 0)
	ZEND_ARG_OBJ_INFO(0, share_handle, GCurlShareHandle, 0)
ZEND_END_ARG_INFO()

ZEND_FUNCTION(gcurl_version);
ZEND_FUNCTION(gcurl_init);
ZEND_FUNCTION(gcurl_impersonate);
ZEND_FUNCTION(gcurl_setopt);
ZEND_FUNCTION(gcurl_setopt_array);
ZEND_FUNCTION(gcurl_exec);
ZEND_FUNCTION(gcurl_getinfo);
ZEND_FUNCTION(gcurl_errno);
ZEND_FUNCTION(gcurl_error);
ZEND_FUNCTION(gcurl_strerror);
ZEND_FUNCTION(gcurl_reset);
ZEND_FUNCTION(gcurl_close);
ZEND_FUNCTION(gcurl_copy_handle);
ZEND_FUNCTION(gcurl_multi_init);
ZEND_FUNCTION(gcurl_multi_add_handle);
ZEND_FUNCTION(gcurl_multi_remove_handle);
ZEND_FUNCTION(gcurl_multi_exec);
ZEND_FUNCTION(gcurl_multi_select);
ZEND_FUNCTION(gcurl_multi_info_read);
ZEND_FUNCTION(gcurl_multi_getcontent);
ZEND_FUNCTION(gcurl_multi_errno);
ZEND_FUNCTION(gcurl_multi_strerror);
ZEND_FUNCTION(gcurl_multi_close);
ZEND_FUNCTION(gcurl_multi_setopt);
ZEND_FUNCTION(gcurl_share_init);
ZEND_FUNCTION(gcurl_share_setopt);
ZEND_FUNCTION(gcurl_share_close);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(gcurl_version, arginfo_gcurl_version)
	ZEND_FE(gcurl_init, arginfo_gcurl_init)
	ZEND_FE(gcurl_impersonate, arginfo_gcurl_impersonate)
	ZEND_FE(gcurl_setopt, arginfo_gcurl_setopt)
	ZEND_FE(gcurl_setopt_array, arginfo_gcurl_setopt_array)
	ZEND_FE(gcurl_exec, arginfo_gcurl_exec)
	ZEND_FE(gcurl_getinfo, arginfo_gcurl_getinfo)
	ZEND_FE(gcurl_errno, arginfo_gcurl_errno)
	ZEND_FE(gcurl_error, arginfo_gcurl_error)
	ZEND_FE(gcurl_strerror, arginfo_gcurl_strerror)
	ZEND_FE(gcurl_reset, arginfo_gcurl_reset)
	ZEND_FE(gcurl_close, arginfo_gcurl_close)
	ZEND_FE(gcurl_copy_handle, arginfo_gcurl_copy_handle)
	ZEND_FE(gcurl_multi_init, arginfo_gcurl_multi_init)
	ZEND_FE(gcurl_multi_add_handle, arginfo_gcurl_multi_add_handle)
	ZEND_FE(gcurl_multi_remove_handle, arginfo_gcurl_multi_remove_handle)
	ZEND_FE(gcurl_multi_exec, arginfo_gcurl_multi_exec)
	ZEND_FE(gcurl_multi_select, arginfo_gcurl_multi_select)
	ZEND_FE(gcurl_multi_info_read, arginfo_gcurl_multi_info_read)
	ZEND_FE(gcurl_multi_getcontent, arginfo_gcurl_multi_getcontent)
	ZEND_FE(gcurl_multi_errno, arginfo_gcurl_multi_errno)
	ZEND_FE(gcurl_multi_strerror, arginfo_gcurl_multi_strerror)
	ZEND_FE(gcurl_multi_close, arginfo_gcurl_multi_close)
	ZEND_FE(gcurl_multi_setopt, arginfo_gcurl_multi_setopt)
	ZEND_FE(gcurl_share_init, arginfo_gcurl_share_init)
	ZEND_FE(gcurl_share_setopt, arginfo_gcurl_share_setopt)
	ZEND_FE(gcurl_share_close, arginfo_gcurl_share_close)
	ZEND_FE_END
};

static void register_gcurl_handle_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("GCURLOPT_URL", CURLOPT_URL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PORT", CURLOPT_PORT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PROXY", CURLOPT_PROXY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PROXYPORT", CURLOPT_PROXYPORT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PROXYTYPE", CURLOPT_PROXYTYPE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PROXYUSERPWD", CURLOPT_PROXYUSERPWD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_INTERFACE", CURLOPT_INTERFACE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_RESOLVE", CURLOPT_RESOLVE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_CONNECT_TO", CURLOPT_CONNECT_TO, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_RETURNTRANSFER", GCURLOPT_RETURNTRANSFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_BINARYTRANSFER", GCURLOPT_BINARYTRANSFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_HEADER", CURLOPT_HEADER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_HTTPHEADER", CURLOPT_HTTPHEADER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_HTTP_VERSION", CURLOPT_HTTP_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_FOLLOWLOCATION", CURLOPT_FOLLOWLOCATION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_MAXREDIRS", CURLOPT_MAXREDIRS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_AUTOREFERER", CURLOPT_AUTOREFERER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_USERAGENT", CURLOPT_USERAGENT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_REFERER", CURLOPT_REFERER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_ENCODING", CURLOPT_ENCODING, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_CUSTOMREQUEST", CURLOPT_CUSTOMREQUEST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_HTTPGET", CURLOPT_HTTPGET, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_NOBODY", CURLOPT_NOBODY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_FAILONERROR", CURLOPT_FAILONERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_POST", CURLOPT_POST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_POSTFIELDS", CURLOPT_POSTFIELDS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_POSTFIELDSIZE", CURLOPT_POSTFIELDSIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PUT", CURLOPT_PUT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_USERPWD", CURLOPT_USERPWD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_USERNAME", CURLOPT_USERNAME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_PASSWORD", CURLOPT_PASSWORD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_HTTPAUTH", CURLOPT_HTTPAUTH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_COOKIE", CURLOPT_COOKIE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_COOKIEFILE", CURLOPT_COOKIEFILE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_COOKIEJAR", CURLOPT_COOKIEJAR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_COOKIESESSION", CURLOPT_COOKIESESSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_SSL_VERIFYPEER", CURLOPT_SSL_VERIFYPEER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_SSL_VERIFYHOST", CURLOPT_SSL_VERIFYHOST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_CAINFO", CURLOPT_CAINFO, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_CAPATH", CURLOPT_CAPATH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_SSLCERT", CURLOPT_SSLCERT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_SSLKEY", CURLOPT_SSLKEY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_SSL_CIPHER_LIST", CURLOPT_SSL_CIPHER_LIST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_TIMEOUT", CURLOPT_TIMEOUT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_TIMEOUT_MS", CURLOPT_TIMEOUT_MS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_CONNECTTIMEOUT", CURLOPT_CONNECTTIMEOUT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_CONNECTTIMEOUT_MS", CURLOPT_CONNECTTIMEOUT_MS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_WRITEFUNCTION", CURLOPT_WRITEFUNCTION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_HEADERFUNCTION", CURLOPT_HEADERFUNCTION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_FILE", CURLOPT_FILE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLOPT_VERBOSE", CURLOPT_VERBOSE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_HTTP_CODE", CURLINFO_HTTP_CODE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_RESPONSE_CODE", CURLINFO_RESPONSE_CODE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_EFFECTIVE_URL", CURLINFO_EFFECTIVE_URL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_TOTAL_TIME", CURLINFO_TOTAL_TIME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_NAMELOOKUP_TIME", CURLINFO_NAMELOOKUP_TIME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_CONNECT_TIME", CURLINFO_CONNECT_TIME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_PRETRANSFER_TIME", CURLINFO_PRETRANSFER_TIME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_STARTTRANSFER_TIME", CURLINFO_STARTTRANSFER_TIME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_REDIRECT_TIME", CURLINFO_REDIRECT_TIME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_REDIRECT_COUNT", CURLINFO_REDIRECT_COUNT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_REDIRECT_URL", CURLINFO_REDIRECT_URL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_SIZE_DOWNLOAD_T", CURLINFO_SIZE_DOWNLOAD_T, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_SIZE_UPLOAD_T", CURLINFO_SIZE_UPLOAD_T, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_HEADER_SIZE", CURLINFO_HEADER_SIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_REQUEST_SIZE", CURLINFO_REQUEST_SIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_CONTENT_TYPE", CURLINFO_CONTENT_TYPE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_PRIMARY_IP", CURLINFO_PRIMARY_IP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_PRIMARY_PORT", CURLINFO_PRIMARY_PORT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_LOCAL_IP", CURLINFO_LOCAL_IP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_LOCAL_PORT", CURLINFO_LOCAL_PORT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_SCHEME", CURLINFO_SCHEME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLINFO_HTTP_VERSION", CURLINFO_HTTP_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLM_OK", CURLM_OK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLM_BAD_HANDLE", CURLM_BAD_HANDLE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLMSG_DONE", CURLMSG_DONE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_OK", CURLE_OK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_UNSUPPORTED_PROTOCOL", CURLE_UNSUPPORTED_PROTOCOL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_FAILED_INIT", CURLE_FAILED_INIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_URL_MALFORMAT", CURLE_URL_MALFORMAT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_COULDNT_RESOLVE_HOST", CURLE_COULDNT_RESOLVE_HOST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_COULDNT_CONNECT", CURLE_COULDNT_CONNECT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_OPERATION_TIMEDOUT", CURLE_OPERATION_TIMEDOUT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLE_SSL_CONNECT_ERROR", CURLE_SSL_CONNECT_ERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLPROXY_HTTP", CURLPROXY_HTTP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLPROXY_HTTPS", CURLPROXY_HTTPS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLPROXY_SOCKS4", CURLPROXY_SOCKS4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLPROXY_SOCKS5", CURLPROXY_SOCKS5, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLPROXY_SOCKS4A", CURLPROXY_SOCKS4A, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLSHOPT_NONE", CURLSHOPT_NONE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLSHOPT_SHARE", CURLSHOPT_SHARE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURLSHOPT_UNSHARE", CURLSHOPT_UNSHARE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURL_LOCK_DATA_COOKIE", CURL_LOCK_DATA_COOKIE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURL_LOCK_DATA_DNS", CURL_LOCK_DATA_DNS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("GCURL_LOCK_DATA_SSL_SESSION", CURL_LOCK_DATA_SSL_SESSION, CONST_PERSISTENT);
}

static zend_class_entry *register_class_GCurlHandle(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "GCurlHandle", NULL);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_GCurlMultiHandle(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "GCurlMultiHandle", NULL);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}

static zend_class_entry *register_class_GCurlShareHandle(void)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "GCurlShareHandle", NULL);
	class_entry = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL|ZEND_ACC_NOT_SERIALIZABLE);

	return class_entry;
}
