#include "php.h"
#include "php_gcurl.h"

void gcurl_register_constants(int module_number)
{
    /* Options */
    REGISTER_LONG_CONSTANT("GCURLOPT_URL", CURLOPT_URL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PORT", CURLOPT_PORT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PROXY", CURLOPT_PROXY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PROXYPORT", CURLOPT_PROXYPORT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PROXYTYPE", CURLOPT_PROXYTYPE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PROXYUSERPWD", CURLOPT_PROXYUSERPWD, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_INTERFACE", CURLOPT_INTERFACE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_RESOLVE", CURLOPT_RESOLVE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_CONNECT_TO", CURLOPT_CONNECT_TO, CONST_CS | CONST_PERSISTENT);

    /* Custom / PHP options */
    REGISTER_LONG_CONSTANT("GCURLOPT_RETURNTRANSFER", GCURLOPT_RETURNTRANSFER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_BINARYTRANSFER", GCURLOPT_BINARYTRANSFER, CONST_CS | CONST_PERSISTENT);

    /* HTTP */
    REGISTER_LONG_CONSTANT("GCURLOPT_HEADER", CURLOPT_HEADER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_HTTPHEADER", CURLOPT_HTTPHEADER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_HTTP_VERSION", CURLOPT_HTTP_VERSION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_FOLLOWLOCATION", CURLOPT_FOLLOWLOCATION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_MAXREDIRS", CURLOPT_MAXREDIRS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_AUTOREFERER", CURLOPT_AUTOREFERER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_USERAGENT", CURLOPT_USERAGENT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_REFERER", CURLOPT_REFERER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_ENCODING", CURLOPT_ENCODING, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_CUSTOMREQUEST", CURLOPT_CUSTOMREQUEST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_HTTPGET", CURLOPT_HTTPGET, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_NOBODY", CURLOPT_NOBODY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_FAILONERROR", CURLOPT_FAILONERROR, CONST_CS | CONST_PERSISTENT);

    /* POST */
    REGISTER_LONG_CONSTANT("GCURLOPT_POST", CURLOPT_POST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_POSTFIELDS", CURLOPT_POSTFIELDS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_POSTFIELDSIZE", CURLOPT_POSTFIELDSIZE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PUT", CURLOPT_PUT, CONST_CS | CONST_PERSISTENT);

    /* Auth */
    REGISTER_LONG_CONSTANT("GCURLOPT_USERPWD", CURLOPT_USERPWD, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_USERNAME", CURLOPT_USERNAME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_PASSWORD", CURLOPT_PASSWORD, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_HTTPAUTH", CURLOPT_HTTPAUTH, CONST_CS | CONST_PERSISTENT);

    /* Cookies */
    REGISTER_LONG_CONSTANT("GCURLOPT_COOKIE", CURLOPT_COOKIE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_COOKIEFILE", CURLOPT_COOKIEFILE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_COOKIEJAR", CURLOPT_COOKIEJAR, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_COOKIESESSION", CURLOPT_COOKIESESSION, CONST_CS | CONST_PERSISTENT);

    /* SSL/TLS */
    REGISTER_LONG_CONSTANT("GCURLOPT_SSL_VERIFYPEER", CURLOPT_SSL_VERIFYPEER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_SSL_VERIFYHOST", CURLOPT_SSL_VERIFYHOST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_CAINFO", CURLOPT_CAINFO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_CAPATH", CURLOPT_CAPATH, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_SSLCERT", CURLOPT_SSLCERT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_SSLKEY", CURLOPT_SSLKEY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_SSL_CIPHER_LIST", CURLOPT_SSL_CIPHER_LIST, CONST_CS | CONST_PERSISTENT);

    /* Timeouts */
    REGISTER_LONG_CONSTANT("GCURLOPT_TIMEOUT", CURLOPT_TIMEOUT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_TIMEOUT_MS", CURLOPT_TIMEOUT_MS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_CONNECTTIMEOUT", CURLOPT_CONNECTTIMEOUT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_CONNECTTIMEOUT_MS", CURLOPT_CONNECTTIMEOUT_MS, CONST_CS | CONST_PERSISTENT);

    /* Callbacks & Stream */
    REGISTER_LONG_CONSTANT("GCURLOPT_WRITEFUNCTION", CURLOPT_WRITEFUNCTION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_HEADERFUNCTION", CURLOPT_HEADERFUNCTION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_FILE", CURLOPT_FILE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLOPT_VERBOSE", CURLOPT_VERBOSE, CONST_CS | CONST_PERSISTENT);

    /* Info constants */
    REGISTER_LONG_CONSTANT("GCURLINFO_HTTP_CODE", CURLINFO_HTTP_CODE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_RESPONSE_CODE", CURLINFO_RESPONSE_CODE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_EFFECTIVE_URL", CURLINFO_EFFECTIVE_URL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_TOTAL_TIME", CURLINFO_TOTAL_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_NAMELOOKUP_TIME", CURLINFO_NAMELOOKUP_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_CONNECT_TIME", CURLINFO_CONNECT_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_PRETRANSFER_TIME", CURLINFO_PRETRANSFER_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_STARTTRANSFER_TIME", CURLINFO_STARTTRANSFER_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_REDIRECT_TIME", CURLINFO_REDIRECT_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_REDIRECT_COUNT", CURLINFO_REDIRECT_COUNT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_REDIRECT_URL", CURLINFO_REDIRECT_URL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_SIZE_DOWNLOAD_T", CURLINFO_SIZE_DOWNLOAD_T, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_SIZE_UPLOAD_T", CURLINFO_SIZE_UPLOAD_T, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_HEADER_SIZE", CURLINFO_HEADER_SIZE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_REQUEST_SIZE", CURLINFO_REQUEST_SIZE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_CONTENT_TYPE", CURLINFO_CONTENT_TYPE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_PRIMARY_IP", CURLINFO_PRIMARY_IP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_PRIMARY_PORT", CURLINFO_PRIMARY_PORT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_LOCAL_IP", CURLINFO_LOCAL_IP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_LOCAL_PORT", CURLINFO_LOCAL_PORT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_SCHEME", CURLINFO_SCHEME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLINFO_HTTP_VERSION", CURLINFO_HTTP_VERSION, CONST_CS | CONST_PERSISTENT);

    /* Multi constants */
    REGISTER_LONG_CONSTANT("GCURLM_OK", CURLM_OK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLM_BAD_HANDLE", CURLM_BAD_HANDLE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLMSG_DONE", CURLMSG_DONE, CONST_CS | CONST_PERSISTENT);

    /* Error codes */
    REGISTER_LONG_CONSTANT("GCURLE_OK", CURLE_OK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_UNSUPPORTED_PROTOCOL", CURLE_UNSUPPORTED_PROTOCOL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_FAILED_INIT", CURLE_FAILED_INIT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_URL_MALFORMAT", CURLE_URL_MALFORMAT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_COULDNT_RESOLVE_HOST", CURLE_COULDNT_RESOLVE_HOST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_COULDNT_CONNECT", CURLE_COULDNT_CONNECT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_OPERATION_TIMEDOUT", CURLE_OPERATION_TIMEDOUT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLE_SSL_CONNECT_ERROR", CURLE_SSL_CONNECT_ERROR, CONST_CS | CONST_PERSISTENT);

    /* Proxy constants */
    REGISTER_LONG_CONSTANT("GCURLPROXY_HTTP", CURLPROXY_HTTP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLPROXY_HTTPS", CURLPROXY_HTTPS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLPROXY_SOCKS4", CURLPROXY_SOCKS4, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLPROXY_SOCKS5", CURLPROXY_SOCKS5, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLPROXY_SOCKS4A", CURLPROXY_SOCKS4A, CONST_CS | CONST_PERSISTENT);

    /* Share constants */
    REGISTER_LONG_CONSTANT("GCURLSHOPT_NONE", CURLSHOPT_NONE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLSHOPT_SHARE", CURLSHOPT_SHARE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURLSHOPT_UNSHARE", CURLSHOPT_UNSHARE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURL_LOCK_DATA_COOKIE", CURL_LOCK_DATA_COOKIE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURL_LOCK_DATA_DNS", CURL_LOCK_DATA_DNS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("GCURL_LOCK_DATA_SSL_SESSION", CURL_LOCK_DATA_SSL_SESSION, CONST_CS | CONST_PERSISTENT);
}
